public with sharing class ResponseJSONWrapper {
   @AuraEnabled
    public String spouse;
   @AuraEnabled
     public String contactRecordType;
     @AuraEnabled
     public Date birthDate;
     @AuraEnabled
     public String mobile;
     @AuraEnabled
     public String mailingAddress ;
     @AuraEnabled
     public String otherAddress;
     @AuraEnabled
     public String languages;
     @AuraEnabled
     public String level;
     @AuraEnabled
     public String Description;
}
